export const ROLES = {
  ADMIN: "ADMIN",
  CLIENTE: "CLIENTE",
  COORDINADOR: "COORDINADOR",
  VISUALIZACION: "VISUALIZACION",
  REENCAUCHE_USER: "REENCAUCHE_USER",
  VENDEDOR_B2C: "VENDEDOR B2C",
  VENDEDOR_B2B: "VENDEDOR B2B"
};
